=== MaxIV-KitsControls/lib-maxiv-dsconfig/dsconfig/schema/dsconfig.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Tango device generator JSON canonical format",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "_title": {
      "type": "string"
    },
    "_date": {
      "type": "string"
    },
    "_source": {
      "type": "string"
    },
    "_version": {
      "enum": [
        2
      ]
    },
    "servers": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[\\-\\w]+$": {
          "$ref": "#definitions/server"
        }
      }
    },
    "classes": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#definitions/device"
      },
      "properties": {
        "properties": {
          "$ref": "#definitions/property"
        }
      }
    }
  },
  "definitions": {
    "server": {
      "type": "object",
      "patternProperties": {
        "^[\\-\\w]+$": {
          "$ref": "#definitions/instance"
        }
      }
    },
    "instance": {
      "type": "object",
      "patternProperties": {
        "^[\\-\\w]+$": {
          "$ref": "#definitions/class"
        }
      }
    },
    "class": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[\\-\\w]+/[\\-\\w]+/[\\-\\w]+$": {
          "$ref": "#definitions/device"
        }
      }
    },
    "device": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "properties": {
          "$ref": "#definitions/properties"
        },
        "attribute_properties": {
          "$ref": "#definitions/attribute_properties"
        }
      }
    },
    "properties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#definitions/property"
      }
    },
    "property": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string"
      }
    },
    "attribute_properties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#definitions/attribute_property"
      }
    },
    "attribute_property": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/property"
      }
    },
    "class_property": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "$ref": "#definitions/property"
      }
    }
  }
}

=== MaxIV-KitsControls/lib-maxiv-dsconfig/test/files/sample_db.json
{
  "classes": {
    "ScienceYetChallenge": {
      "properties": {
        "RecordHead": ["wparks"],
        "HotItself": ["tracy32"],
        "DetailFear": ["haynesashlee"]
      }
    },
    "Site": {
      "attribute_properties": {
        "Approach": {
          "delta_t": ["16"],
          "__value": ["-22"],
          "max_warning": ["-56"],
          "unit": ["79"]
        }
      },
      "properties": { "ListenLess": ["melindahanson"] }
    },
    "TreatHerselfPublic": {
      "attribute_properties": {
        "ResearchHeadOff": { "archive_period": ["-99"] }
      },
      "properties": { "HowShouldWorldLong": ["joshuaholmes"] }
    },
    "RecognizeRequire": {
      "attribute_properties": {
        "RequireGirlReflect": { "max_warning": ["-31"] }
      },
      "properties": { "Teacher": ["chelsea64"] }
    }
  },
  "servers": {
    "AttentionSea": {
      "1JY-48-XAK": {
        "HugeClassBook": {
          "WEST/WILL/PROFESSIONAL-7": {
            "attribute_properties": {
              "MagazineLaugh": { "max_warning": ["46"], "format": ["16"] }
            },
            "properties": {
              "Car": ["evansjessica"],
              "ShareLastNone": ["lindsey30"],
              "ViewDreamShouldWhileOpen": ["cbanks"]
            }
          }
        },
        "Life": {
          "CONCERN/ENVIRONMENTAL/THEMSELVES-1": {
            "properties": {
              "DemocraticLocal": ["coledaniel", "juliecook", "eacosta"]
            }
          },
          "SAME/PROGRAM/SAFE-10": {
            "properties": {
              "Trouble": ["ovargas"],
              "EnergyOneOff": ["carolinehendrix"],
              "KeySkinItWalkReach": [
                "mobrien",
                "davisalexandra",
                "fburnett",
                "qroberts"
              ]
            }
          }
        }
      },
      "AXQ-AP-M8O7": {
        "Rich": {
          "WEST/OFFICER/COMPUTER-1": {
            "attribute_properties": {
              "DropCaseHere": { "abs_change": ["77"] }
            },
            "properties": {
              "SeemChangeHusbandMeetLot": ["alecfreeman"],
              "TaskFocusGroupDecade": ["thomasmarie", "burtonjennifer"]
            }
          },
          "SITUATION/SIZE/WAY-4": {
            "properties": {
              "TeacherThereKitchenCapital": ["wayne35", "amberward"],
              "NothingRelateAgainShoulderLaugh": ["yhart"],
              "UseTurn": ["dustinjones", "joseph12", "esparzaandrew"]
            }
          },
          "ABOVE/AWAY/TEAM-9": {
            "attribute_properties": {
              "TreatBetterToward": { "max_warning": ["-92"] }
            },
            "properties": { "CallThem": ["marissa86", "lisa32"] }
          },
          "REVEAL/BAD/BODY-6": { "properties": { "Tax": ["jacksonpatricia"] } },
          "ROLE/HERSELF/SKIN-1": {
            "attribute_properties": {
              "Recent": { "rel_change": ["-32"], "archive_rel_change": ["-15"] }
            },
            "properties": { "SeekSideMean": ["fyoung"] }
          },
          "SO/ROOM/SECTION-7": {
            "properties": { "LeaderInOpportunity": ["qrodriguez"] }
          },
          "FRONT/LOT/THERE-2": {
            "properties": { "Base": ["xbradley", "psmith", "william19"] }
          }
        }
      },
      "WA-6": {
        "IncludeParticipantMonth": {
          "WEAR/LINE/QUESTION-7": {
            "properties": {
              "ParentHealthPositiveMinuteAccording": ["scottthompson"],
              "OpportunityPassTwo": [
                "smithjennifer",
                "michele44",
                "debbieguzman",
                "teresaallen"
              ]
            }
          }
        },
        "EnergyHeavyBuy": {
          "THINK/DAY/WIN-4": {
            "properties": {
              "HeSendCitizen": [
                "mary84",
                "wilcoxdaniel",
                "audreybrown",
                "cookjohn",
                "lewisjeffrey"
              ]
            }
          }
        },
        "Campaign": {
          "THANK/MODEL/POPULATION-10": {
            "attribute_properties": {
              "MeetingSitThat": {
                "rel_change": ["-19"],
                "archive_abs_change": ["98"]
              },
              "IssueDevelop": { "archive_period": ["71"] },
              "IndeedCoverFact": { "__value": ["36"] },
              "Tell": { "mode": ["35"] }
            },
            "properties": { "Suddenly": ["edwardsjill", "xbarajas"] }
          }
        },
        "Factor": {
          "TRY/DIFFICULT/ON-1": {
            "attribute_properties": {
              "MeasureOld": { "min_warning": ["84"], "mode": ["79"] }
            },
            "properties": { "AssumeTooGuess": ["nmartinez"] }
          }
        }
      },
      "2N-UL7": {
        "WithinCouldThem": {
          "SHORT/WONDER/NATURAL-8": {
            "properties": {
              "Expect": ["rojassandra", "leemelissa", "sherri83"]
            }
          },
          "PROVE/CONTROL/MAGAZINE-0": {
            "attribute_properties": {
              "Line": { "__value": ["-82"], "unit": ["-16"] },
              "Side": { "unit": ["-32"] },
              "ListenHappen": { "__value": ["82"] }
            },
            "properties": { "Place": ["peterboone", "hbarron", "rlynch"] }
          }
        }
      },
      "X": {
        "Media": {
          "PREVENT/WHAT/SHARE-6": { "properties": { "Trouble": ["joe60"] } }
        }
      },
      "CV3-L": {
        "MaybeHisTeacher": {
          "ANYONE/WE/SET-10": {
            "properties": {
              "ManCollectionConsiderSomeonePolitics": ["arnoldkyle"],
              "GunMediaPresentFather": ["denise75"]
            }
          },
          "PROTECT/NICE/LAW-4": {
            "properties": {
              "DogPowerWhom": ["wmanning"],
              "GetAwayParticularly": ["jennifercastillo"]
            }
          }
        },
        "NextDecisionOver": {
          "THOUGHT/OCCUR/NEXT-3": {
            "properties": {
              "StockVariousFeelProgramBag": ["miahoward", "ywright"]
            }
          }
        },
        "Article": {
          "INSTEAD/ISSUE/FOR-0": {
            "properties": {
              "SubjectWorldUsuallyFeelDebate": ["davidterry"],
              "RedSurfaceThemBlack": ["matthew12"]
            }
          },
          "SKILL/COLD/EVERYTHING-4": {
            "attribute_properties": {
              "Central": { "min_alarm": ["-71"] },
              "ResearchKitchen": {
                "max_alarm": ["48"],
                "min_warning": ["28"],
                "mode": ["-65"]
              },
              "RestFast": { "delta_val": ["-94"] }
            },
            "properties": {
              "ShortPriceSongOk": [
                "vbrown",
                "billygarcia",
                "vgrimes",
                "wsmith",
                "rarcher",
                "daniel61"
              ]
            }
          },
          "GET/NOR/FEW-0": {
            "attribute_properties": {
              "NorSuffer": { "archive_rel_change": ["-9"], "mode": ["-7"] },
              "EatRaise": { "abs_change": ["85"] },
              "OpenWaterFire": { "archive_rel_change": ["72"] }
            },
            "properties": { "Treat": ["urodriguez"] }
          }
        }
      }
    },
    "RecentlyOnceCheck": {
      "XS0-OJR5": {
        "DetermineExplainNearly": {
          "TEN/ABILITY/TAX-4": {
            "attribute_properties": {
              "ExactlyLater": { "__value": ["-86"] },
              "WestMostMoment": { "standard_unit": ["59"] },
              "Fact": { "max_value": ["-5"] }
            },
            "properties": {
              "AlwaysSixDetermine": ["brian58"],
              "LikelyColorKeepOpen": ["apatton", "adam35"]
            }
          }
        }
      },
      "S-V89-2PUQP": {
        "West": {
          "STAFF/APPLY/ENOUGH-4": {
            "properties": { "ReturnMeasureProjectAccount": ["jocelynleblanc"] }
          }
        }
      },
      "3FSE": {
        "HundredRequireCup": {
          "PICK/APPLY/MATERIAL-5": {
            "properties": {
              "MoveJustWay": ["hramirez"],
              "ConcernBoard": ["xgaines"]
            }
          },
          "CHOOSE/NOR/COLLECTION-0": {
            "properties": { "ClassPrettyThanContainResource": ["jeffrey70"] }
          },
          "DAUGHTER/ACROSS/REACH-3": {
            "attribute_properties": { "Smile": { "max_value": ["-23"] } },
            "properties": { "DirectionExpect": ["qlopez"] }
          },
          "TASK/POSITIVE/OUTSIDE-7": {
            "properties": {
              "FieldPutTodayGreatTotal": ["kylecollins"],
              "FoodLawyer": ["denisesharp"]
            }
          },
          "PROGRAM/ME/IDEA-2": {
            "properties": { "MainTreatmentImprove": ["amber81"] }
          }
        }
      },
      "F5-7T-R": {
        "StandardThrough": {
          "HEALTH/EVIDENCE/ANY-7": {
            "properties": {
              "AtPutA": ["kathleen53"],
              "AdmitGoSell": ["dudleymariah"],
              "TodayFieldPlantServe": ["bkim"],
              "BackArtist": ["diane28"]
            }
          },
          "HER/ITEM/RADIO-7": {
            "attribute_properties": {
              "NightPresidentVery": { "max_value": ["60"] }
            },
            "properties": {
              "Father": ["kwoods", "michaelsimon"],
              "MoveRealizeEnterEatCentury": ["warnercaitlin", "eolsen"]
            }
          },
          "HUSBAND/ARGUE/EXECUTIVE-5": {
            "properties": {
              "SeriousMovementFollowMatter": ["jaredwilliams", "marissasalinas"]
            }
          },
          "PROVIDE/AUTHORITY/HOME-3": {
            "attribute_properties": {
              "LandStructureStop": { "unit": ["-23"] },
              "BallDog": { "label": ["12"] }
            },
            "properties": {
